import React, { useState } from 'react';
import {
  Dialog, DialogTitle, DialogContent, DialogActions,
  TextField, Button, FormControlLabel, Checkbox,
  Typography, Radio, RadioGroup, Box, IconButton
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import api from '../../../services/api';

function ResetPasswordModal({ open, onClose, userId, username }) {
  const [passwordType, setPasswordType] = useState('random');
  const [specificPassword, setSpecificPassword] = useState('');
  const [randomPassword, setRandomPassword] = useState('');
  const [sendEmail, setSendEmail] = useState(true);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  
  // Fetch a backend-generated password when modal opens
  React.useEffect(() => {
    if (open) {
      fetchGeneratedPassword();
    }
  }, [open]);

  // Fetch a backend-generated password
  const fetchGeneratedPassword = async () => {
    try {
      // Call the backend to generate a secure password
      const response = await api.get('/api/users/generate-password');

      if (response.data && response.data.password) {
        setRandomPassword(response.data.password);
      } else {
        // Fallback message if backend doesn't return a password
        setRandomPassword('(Password will be generated by system)');
      }
    } catch (error) {
      // Fallback message if API call fails
      setRandomPassword('(Password will be generated by system)');
    }
  };
  
  // Reset user password
  const handleResetPassword = async () => {
    setLoading(true);
    setError(null);

    try {
      // If using specific password, include it in the request
      // If using random, don't send password (backend will generate it)
      const requestData = {
        sendEmail,
        useRandomPassword: passwordType === 'random'
      };

      // Only include password if using a specific one
      if (passwordType === 'specific') {
        requestData.password = specificPassword;
      }

      const response = await api.put(`/api/users/${userId}/password`, requestData);

      // If backend generated a random password, get it from the response
      if (passwordType === 'random' && response.data && response.data.generatedPassword) {
        setRandomPassword(response.data.generatedPassword);
      }

      onClose();
      // Show success notification
    } catch (error) {
      setError('Failed to reset password. Please try again.');
    } finally {
      setLoading(false);
    }
  };
  
  // Validate password
  const isPasswordValid = () => {
    if (passwordType === 'random') return true;
    
    const password = specificPassword;
    // Check if password is at least 8 characters long and contains uppercase, lowercase, number, and special character
    const hasUppercase = /[A-Z]/.test(password);
    const hasLowercase = /[a-z]/.test(password);
    const hasNumber = /[0-9]/.test(password);
    const hasSpecial = /[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/.test(password);
    const isLongEnough = password.length >= 8;
    
    return hasUppercase && hasLowercase && hasNumber && hasSpecial && isLongEnough;
  };
  
  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle>
        Reset Password for User: {username}
        <IconButton
          aria-label="close"
          onClick={onClose}
          sx={{ position: 'absolute', right: 8, top: 8 }}
        >
          <CloseIcon />
        </IconButton>
      </DialogTitle>
      
      <DialogContent dividers>
        {error && (
          <Box sx={{ mb: 2 }}>
            <Alert severity="error">{error}</Alert>
          </Box>
        )}
        
        <Typography variant="h6" gutterBottom>
          Reset Password Options
        </Typography>
        
        <RadioGroup
          value={passwordType}
          onChange={(e) => setPasswordType(e.target.value)}
        >
          <FormControlLabel
            value="specific"
            control={<Radio />}
            label="Set specific password:"
          />
          
          <Box sx={{ ml: 4, mb: 2 }}>
            <TextField
              fullWidth
              type="text"
              value={specificPassword}
              onChange={(e) => setSpecificPassword(e.target.value)}
              disabled={passwordType !== 'specific'}
              error={passwordType === 'specific' && !isPasswordValid()}
              helperText={
                passwordType === 'specific' && !isPasswordValid() ?
                'Password must contain at least 8 characters including uppercase, lowercase, number, and special character' :
                ''
              }
            />
          </Box>
          
          <FormControlLabel
            value="random"
            control={<Radio />}
            label="Generate random password:"
          />
          
          <Box sx={{ ml: 4, mb: 2, display: 'flex', alignItems: 'center' }}>
            <TextField
              value={randomPassword}
              disabled
              sx={{ flexGrow: 1 }}
            />
            <Button
              onClick={fetchGeneratedPassword}
              sx={{ ml: 1 }}
              disabled={passwordType !== 'random'}
            >
              Regenerate
            </Button>
          </Box>
        </RadioGroup>
        
        <FormControlLabel
          control={
            <Checkbox
              checked={sendEmail}
              onChange={(e) => setSendEmail(e.target.checked)}
            />
          }
          label="Send password reset email to user"
        />
        
        <Typography variant="body2" color="textSecondary" sx={{ mt: 2 }}>
          Password must contain at least 8 characters including uppercase, lowercase, number, and special character.
        </Typography>
      </DialogContent>
      
      <DialogActions>
        <Button onClick={onClose} color="inherit">
          Cancel
        </Button>
        <Button 
          onClick={handleResetPassword} 
          variant="contained" 
          color="primary"
          disabled={loading || (passwordType === 'specific' && !isPasswordValid())}
        >
          Reset Password
        </Button>
      </DialogActions>
    </Dialog>
  );
}

export default ResetPasswordModal;